import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import MenuBar from '@/components/MenuBar';
import { LayoutProvider } from '@/components/LayoutContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <LayoutProvider>
          <MenuBar />
          {children}
        </LayoutProvider>
      </body>
    </html>
  );
}
